### ISSUE TITLE
Need struct to map[string]interface{}

### ISSUE THREAD

**Issue by WingGao** [jinzhu/copier#28]
like https://godoc.org/github.com/imdario/mergo#Map
Could we add this feature?

**Comment by ilius** [comment]
Although map keys might be lowercase on first letter, because json keys are usually that way (and json is frequently decoded into  `map[string]interface{}`)
There is also [mapstructure](https://github.com/mitchellh/mapstructure) that copies that map to struct and vice versa.

So do we want to use a specific struct tag (like `json`) or field names as keys?

**Comment by yamil-rivera** [comment]
[encoding/gob](https://golang.org/pkg/encoding/gob) can be a solution for your use case (was for mine). See this stack overflow [answer](https://stackoverflow.com/questions/23033143/is-there-a-built-in-function-in-go-for-making-copies-of-arbitrary-maps) for more context.

**Comment by jinzhu** [comment]
supported.

**Comment by Flipped199** [comment]
I'm sorry to interrupt again, but I noticed that this feature doesn't seem to be implemented
